### ISSUE TITLE
Issues with packaging for android using the dev branch

### ISSUE THREAD

**Issue by HereafterMills** [AgoraIO-Extensions/Agora-Unreal-RTC-SDK#99]
Hi, 

Im getting the following error on packaging android:

Unable to instantiate module 'AgoraPluginLibrary': System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ToolboxVR\Plugins\AgoraPlugin\Source\ThirdParty\AgoraPluginLibrary\Android\Release\armeabi-v7a'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.FileInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.DirectoryInfo.GetFiles(String searchPattern, EnumerationOptions enumerationOptions)
   at System.IO.DirectoryInfo.GetFiles(String searchPattern)
   at AgoraPluginLibrary.GetAllFileNames(String path, String pattern) in D:\ToolboxVR\Plugins\AgoraPlugin\Source\ThirdParty\AgoraPluginLibrary\AgoraPluginLibrary.Build.cs:line 133
   at AgoraPluginLibrary.LoadAndroidLibrary(String librarypath) in D:\ToolboxVR\Plugins\AgoraPlugin\Source\ThirdParty\AgoraPluginLibrary\AgoraPluginLibrary.Build.cs:line 78
   at AgoraPluginLibrary..ctor(ReadOnlyTargetRules Target) in D:\ToolboxVR\Plugins\AgoraPlugin\Source\ThirdParty\AgoraPluginLibrary\AgoraPluginLibrary.Build.cs:line 29
(referenced via Target -> AgoraPlugin.Build.cs)

I have checked, and these are the only files in that folder:
![image](https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/assets/37168482/c3b85a20-109a-424c-9c87-19859ca41a57)

Is it me doing something wrong here? Not sure, but i think it might have been working before with the main branch.

**Comment by HereafterMills** [comment]
so as a fix, i made empty folders with the target arch names. 

But then got a bunch of mediaplayer errors
[Upgrade] Suppress this message by setting 'IncludeOrderVersion = EngineIncludeOrderVersion.Unreal5_2;' in ToolboxVRAndroidAPK.Target.cs.
[Upgrade] Alternatively you can set this to 'EngineIncludeOrderVersion.Latest' to always use the latest include order. This will potentially cause compile errors when integrating new versions of the engine.
[Upgrade]
Determining max actions to execute in parallel (6 physical cores, 12 logical cores)
  Executing up to 6 processes, one per physical core
Building 2 actions with 2 processes...
[1/2] clang++ ToolboxVRAndroidAPK-arm64.so
ld.lld: error: undefined symbol: getMediaPlayerCacheManager
>>> referenced by AgoraMediaPlayer.cpp:301 (D:/ToolboxVR/Plugins/AgoraPlugin/Source/AgoraPlugin/Private/AgoraBluePrintPlugin/AgoraMediaPlayer.cpp:301)
>>>               AgoraPlugin/Module.AgoraPlugin.6_of_7.cpp.o:(UIMediaPlayerCacheManager::RemoveAllCaches())
>>> referenced by AgoraMediaPlayer.cpp:305 (D:/ToolboxVR/Plugins/AgoraPlugin/Source/AgoraPlugin/Private/AgoraBluePrintPlugin/AgoraMediaPlayer.cpp:305)
>>>               AgoraPlugin/Module.AgoraPlugin.6_of_7.cpp.o:(UIMediaPlayerCacheManager::RemoveOldCache())
>>> referenced by AgoraMediaPlayer.cpp:309 (D:/ToolboxVR/Plugins/AgoraPlugin/Source/AgoraPlugin/Private/AgoraBluePrintPlugin/AgoraMediaPlayer.cpp:309)
>>>               AgoraPlugin/Module.AgoraPlugin.6_of_7.cpp.o:(UIMediaPlayerCacheManager::RemoveCacheByUri(FString))
>>> referenced 8 more times
ld.lld: error: undefined symbol: createAgoraRtcEngine
>>> referenced by RtcEngineProxy.cpp:45 (D:/ToolboxVR/Plugins/AgoraPlugin/Source/AgoraPlugin/Private/AgoraCppPlugin/RtcEngineProxy.cpp:45)
>>>               AgoraPlugin/Module.AgoraPlugin.6_of_7.cpp.o:(agora::rtc::ue::RtcEngineProxy::InitInstance())
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
[2/2] WriteMetadata ToolboxVRAndroidAPK.target cancelled


Now, i've removed all references for the media player as im using only voice (for now):
![image](https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/assets/37168482/e96455e0-6816-4fe7-bef7-d0e5745ad1b9)

Will keep you posted

**Comment by HereafterMills** [comment]
So it seems i totally messed up the process to get this to work. The SDK needs to be downloaded and then this plugin overwritten. All the .so files are in there. 

If you find yourself in my position, know that you were not alone 😵‍💫 

Closing this for now.
